language: ruby
rbenv:
  - 2.7.2
branches:
  only:
    - master
    - develop
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    -stage: test
    script: ./bin/rails test
    -stage: deploy
    script: skip
    deploy: &heroku
      provider: heroku
      app: $HEROKU_APP_NAME
      api_key: $HEROKU_API_KEY