language: ruby
rbenv:
  - 2.7.2
branches:
  only:
    - master
jobs:
  include:
    -stage: testing
    script: ./bin/rails test
    -stage: delpoying to heroku
    script: skip
    deploy: &heroku
      provider: heroku
      app: $HEROKU_APP_NAME
      api_key: $HEROKU_API_KEY