version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sport_news_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  kibana:
    image: kibana:7.12.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic
  redis:
    image: redis:6.2.3
    container_name: redis_container
    ports:
    - 6379:6379
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic
    volumes:
      - esdata:/usr/share/elasticsearch/data
networks:
  elastic:
    driver: bridge
volumes:
  esdata:
    driver: local
  pgdata:
    driver: local