version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sport_news_dev
    ports:
      - 5432:5432
  kibana:
    image: kibana:7.12.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    volumes:
      - esdata:/usr/share/elasticsearch/data
networks:
  elastic:
    driver: bridge
volumes:
  esdata:
    driver: local